AWSTemplateFormatVersion: '2010-09-09'
Description: 'Script to produce a dev hyrax server for a given user.'
Parameters:
  KeypairName:
    Type: AWS::EC2::KeyPair::KeyName
  HyraxUserInitials:
    Description: initials of user we are creating the dev server for.
    Default: tt
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-z][a-z]*"
Resources:
  EC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        PublicSubnets:
          !ImportValue "SharedInf-PubNets"
        VpcID:
          !ImportValue "SharedInf-VPCId"
        UserInitials:
          !Ref HyraxUserInitials
        KeypairName:
          !Ref KeypairName
      TemplateURL: https://s3.amazonaws.com/hyrax-cf/singleNodeServer.yaml
      TimeoutInMinutes: '5'
